version: '2'
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
  identical-code:
    enabled: true

exclude_patterns:
  - 'config/'
  - 'dist/'
  - '**/node_modules/'
  - 'scripts/'
  - '**/spec/'
  - '**/test/'
  - '**/tests/'
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - '**/vendor/'
  - '**/*.d.ts'
  - '.github/'
  - 'coverage/'
  - 'docs/'
  - 'logs/'
  - 'multi_env/'
  - '.tmp/'

plugins:
  eslint:
    enabled: true
    channel: 'eslint-8'
    config:
      extensions:
        - .ts
        - .tsx
  fixme:
    enabled: true
  git-legal:
    enabled: true
  nodesecurity:
    enabled: true
  shellcheck:
    enabled: true
  typescript:
    enabled: true
