# Server Configuration
server:
  port: 3000
  host: localhost

# Database Configuration
database:
  url: ${DATABASE_URL}
  pool:
    min: 2
    max: 10

# Client Configuration
client:
  port: 3000
  host: localhost

# Logging Configuration
logging:
  level: info
  format: json
  directory: logs

# Environment
environment: ${NODE_ENV}

# API Configuration
api:
  version: v1
  prefix: /api/v1
  timeout: 30000

# Security
security:
  cors:
    origin: '*'
    methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH']
  rateLimit:
    windowMs: 15 * 60 * 1000
    max: 100 