# Meta-Software Engineering Platform Configuration

# Server Configuration
server:
  port: 5000
  host: "0.0.0.0"
  environment: "development"
  api_base_path: "/api"

# Database Configuration
database:
  url: "postgresql://postgres:postgres@localhost:5432/meta_assistant"
  pool_size: 10
  connection_timeout_ms: 3000

# API Keys (override these with environment variables)
api_keys:
  openai: ""
  azure_openai: ""

# Azure Configuration
azure:
  subscription_id: ""
  tenant_id: ""
  client_id: ""
  client_secret: ""
  openai:
    endpoint: ""
    key: ""
    api_version: "2023-12-01-preview"
    deployment_name: ""

# Application Features
features:
  pattern_recognition: true
  meta_model_generation: true
  specification_generation: true
  template_generation: true
  code_generation: true
  ai_assistance: true

# Logging Configuration
logging:
  level: "info"
  file_path: "logs/app.log"
  max_size_mb: 10
  max_files: 5
  console: true

# Security Configuration
security:
  session_secret: "meta-assistant-secret"
  session_expiry_hours: 24
  cors:
    enabled: true
    origins:
      - "http://localhost:3000"
      - "http://localhost:5000"
      - "http://localhost:5173" 