# Meta-Software Engineering Platform Configuration

# Server Configuration
server:
  port: 5000
  host: "0.0.0.0"
  environment: ${NODE_ENV}
  api_base_path: "/api"
  api:
    version: v1
    prefix: /api/v1
    timeout: 30000

# Database Configuration
database:
  url: ${DATABASE_URL}
  pool:
    min: 2
    max: 10
  pool_size: 10
  connection_timeout_ms: 3000

# Client Configuration
client:
  port: 3000
  host: localhost

# API Keys (override these with environment variables)
api_keys:
  openai: ""
  azure_openai: ""

# Azure Configuration
azure:
  subscription_id: ""
  tenant_id: ""
  client_id: ""
  client_secret: ""
  openai:
    endpoint: ""
    key: ""
    api_version: "2023-12-01-preview"
    deployment_name: ""

# Application Features
features:
  pattern_recognition: true
  meta_model_generation: true
  specification_generation: true
  template_generation: true
  code_generation: true
  ai_assistance: true

# Logging Configuration
logging:
  level: "info"
  format: json
  directory: logs
  file_path: "logs/app.log"
  max_size_mb: 10
  max_files: 5
  console: true

# Security Configuration
security:
  session_secret: "meta-assistant-secret"
  session_expiry_hours: 24
  cors:
    enabled: true
    origin: '*'
    methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH']
    origins:
      - "http://localhost:3000"
      - "http://localhost:5000"
      - "http://localhost:5173"
  rateLimit:
    windowMs: 15 * 60 * 1000
    max: 100
